version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: kh-postgres
    environment:
      POSTGRES_USER: kh_user
      POSTGRES_PASSWORD: kh_password
      POSTGRES_DB: kh_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weaviate:
    image: semitechnologies/weaviate:1.24.10
    container_name: kh-weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  postgres_data:
  weaviate_data: 